version: '3.8'

services:
  petandpeople_test:
    image: mysql:latest
    container_name: petandpeople-test-container
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_SCHEMA}
      MYSQL_USER: ${TEST_DB_USERNAME}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

networks:
  my-network:
    driver: bridge

volumes:
  redis-data: